### ISSUE TITLE
Article store events publisher

### ISSUE THREAD

**Issue by seanwiseman** [libero/walking-skeleton#31]
Add functionality to publish article events via the walking skeleton's [internal event bus](https://github.com/libero/walking-skeleton/blob/master/adr/0001-events-system.md).

Should include the publishing of:
- [x] Article version created `started/succeeded/failed` events
- [x] Article version update `started/succeeded/failed` events
- [x] Article deleted `succeeded/failed` events

**Comment by thewilkybarkid** [comment]
For now we could have:

- `article.version.[delete|post|put].started`
- `article.version.[delete|post|put].completed`
- `article.version.[delete|post|put].failed`

Ties to the API (in name), but this _is_ the processing of the request...

Not sure about the last two though: ok for this purpose, but more generally we might want to consider modelling processes and sub-processes (ie start, step (...), result) in the event bus, rather than just standalone events?

**Comment by seanwiseman** [comment]
OK sounds good. Yes modelling them would also give a nicer context and would perhaps make it simpler to manage any side effects, such as a failure on step `n`.
